name: Publish NuGet Package

on:
  push:
    branches:
      - master # 修改为你的主分支名
    path:
      - 'Directory.Build.props'

jobs:
  build-and-publish:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x' # 修改为你的.NET版本

      - name: Restore NuGet packages
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Pack NuGet package
        run: |
          cd Wlkr.Core.ThreadUtils
          dotnet pack Wlkr.Core.ThreadUtils.csproj  --configuration Release --no-build
          cd ../Wlkr.SafePaddleOCR
          dotnet pack Wlkr.SafePaddleOCR.csproj  --configuration Release --no-build

      - name: Publish NuGet package
        run: dotnet nuget push **/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
